# Generated by Django 5.2.7 on 2025-11-05 10:27

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeAPIResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 8),
                    ("services_overview", 18),
                    ("testimonial_section", 27),
                    ("stats", 31),
                    ("cta", 37),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main headline for the homepage hero.",
                            "max_length": 150,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Short supporting description or tagline.",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Hero background image.", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Add overlay color in hex or rgba (e.g. #00000080).",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": False},
                    ),
                    5: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fade", "Fade In"),
                                ("slide-up", "Slide Up"),
                                ("zoom", "Zoom In"),
                            ],
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("headline", 0),
                                ("subheadline", 1),
                                ("background_image", 2),
                                ("overlay_color", 3),
                                ("button_text", 4),
                                ("button_link", 5),
                                ("animation_style", 6),
                                ("alignment", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 120, "required": True},
                    ),
                    10: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "FontAwesome or Bootstrap icon class, e.g. 'fa-solid fa-cloud'.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    13: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"max_length": 300, "required": True},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon_class", 11),
                                ("title", 12),
                                ("description", 13),
                                ("link_text", 4),
                                ("link_url", 5),
                            ]
                        ],
                        {},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional background color (e.g. #f5f5f5).",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2", "Two Columns"),
                                ("3", "Three Columns"),
                                ("4", "Four Columns"),
                            ]
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_title", 9),
                                ("section_description", 10),
                                ("services", 15),
                                ("background_color", 16),
                                ("columns", 17),
                            ]
                        ],
                        {},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    20: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    21: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    22: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Star rating (1–5).", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("client_name", 19),
                                ("company", 20),
                                ("quote", 21),
                                ("avatar", 22),
                                ("rating", 23),
                            ]
                        ],
                        {},
                    ),
                    25: ("wagtail.blocks.ListBlock", (24,), {}),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("carousel", "Carousel"),
                                ("grid", "Grid"),
                                ("single", "Single Highlight"),
                            ]
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_title", 9),
                                ("testimonials", 25),
                                ("layout_style", 26),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 19), ("value", 19), ("icon_class", 20)]],
                        {},
                    ),
                    29: ("wagtail.blocks.ListBlock", (28,), {}),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("light", "Light"),
                                ("dark", "Dark"),
                                ("accent", "Accent Color"),
                            ]
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("section_title", 20), ("stats", 29), ("theme", 30)]],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": True},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 50, "required": True},
                    ),
                    34: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    35: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("dark", "Dark"),
                                ("light", "Light"),
                            ]
                        },
                    ),
                    36: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {
                            "decimal_places": 2,
                            "help_text": "Opacity value (e.g. 0.5)",
                            "max_digits": 3,
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 32),
                                ("button_text", 33),
                                ("button_link", 34),
                                ("style", 35),
                                ("background_image", 22),
                                ("overlay_opacity", 36),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="footer_note",
            field=models.CharField(
                blank=True, help_text="The footer note for the homepage", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="The meta description for the homepage",
                max_length=3000,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="show_in_navigation",
            field=models.BooleanField(
                default=True, help_text="Check to show this page in the navigation"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="tagline",
            field=models.CharField(
                blank=True, help_text="The tagline for the homepage", max_length=255
            ),
        ),
        migrations.CreateModel(
            name="GlobalSiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_email", models.EmailField(blank=True, max_length=254)),
                ("company_phone", models.CharField(blank=True, max_length=20)),
                ("company_address", models.CharField(blank=True, max_length=255)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                (
                    "theme_color",
                    models.CharField(
                        blank=True,
                        help_text="The theme color for the site",
                        max_length=20,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
                (
                    "site_logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global Site Settings",
                "verbose_name_plural": "Global Site Settings",
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("button_text", models.CharField(blank=True, max_length=255)),
                ("button_link", models.URLField(blank=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_slides",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Slide",
                "verbose_name_plural": "Hero Slides",
            },
        ),
    ]
